//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarjetas.infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recarga
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> Id_Tarjeta { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
    }
}
